site_name: Sinagot Documentation
site_url: https://sinagot.readthedocs.io

markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_if_no_docstring: true
      watch:
        - sinagot

theme:
  name: material

extra_css:
  - custom.css
